### ISSUE TITLE
Unhandled Exception: System.ArgumentException: count must be greater than 0

### ISSUE THREAD

**Issue by wingkinlui** [NRTDP/TDCD_FDR_Calculator#1]
When I am using the FDR calculator to process my data, I keep getting "Unhandled Exception: System.ArgumentException: count must be greater than 0".

My application is quite specific, my LCMS data is from scanning intact histone H3.1. Therefore, in my search space (I used MSPathFinder), I had only included the sequence of human H3.1 and multiple PTMs. Eventually, only a very small number of decoy PrSMs are as good as that found in the forward search. I suspect that it is the little overlap of scores between the forward and decoy PrSMs that caused such error. The search data and spectrum could be downloaded [here](https://mycuhk-my.sharepoint.com/:f:/g/personal/1155064778_link_cuhk_edu_hk/EtDGNq6zugpBrnOaufBlosYBI4XFbV1XZ-gN_WBveuridA?e=dR8ker)

The full error message is as follow:
'''
Calculating Empirical Q-Values.
Calculating Analytical Q-Values.

Unhandled Exception: System.ArgumentException: count must be greater than 0
Parameter name: count
   at TDCD_FDR_Calculator.Program.FitGammaDistributionMaximumLikelihood(Double sum, Double naturalLogSum, Int64 count, Double shapeError) in C:\Users\wingk\OneDrive - The Chinese University of Hong Kong\PhD\Mass Spec Tools\TDCD_FDR_Calculator-master\src\TDCD_FDR_Calculator\Program.cs:line 121
   at TDCD_FDR_Calculator.Program.FitGammaDistributionMaximumLikelihood(IScoreRow[] data) in C:\Users\wingk\OneDrive - The Chinese University of Hong Kong\PhD\Mass Spec Tools\TDCD_FDR_Calculator-master\src\TDCD_FDR_Calculator\Program.cs:line 114
   at TDCD_FDR_Calculator.Program.CalculateAnalyticalQValues(IScoreRow[] forwardHits, IScoreRow[] decoyScores) in C:\Users\wingk\OneDrive - The Chinese University of Hong Kong\PhD\Mass Spec Tools\TDCD_FDR_Calculator-master\src\TDCD_FDR_Calculator\Program.cs:line 79
   at TDCD_FDR_Calculator.Program.Run(String[] args) in C:\Users\wingk\OneDrive - The Chinese University of Hong Kong\PhD\Mass Spec Tools\TDCD_FDR_Calculator-master\src\TDCD_FDR_Calculator\Program.cs:line 37
   at TDCD_FDR_Calculator.Program.Main(String[] args) in C:\Users\wingk\OneDrive - The Chinese University of Hong Kong\PhD\Mass Spec Tools\TDCD_FDR_Calculator-master\src\TDCD_FDR_Calculator\Program.cs:line 20
'''

**Comment by b-early** [comment]
Hello.  We're sorry you're having an issue running the calculator.

I tried running your files and the reason that message is showing up is because all of the decoy scores are negative.  The Analytical Q-Value calculation only works with positive scores.

I looked closer into the files you provided and it looks like the EValue scores are very high in comparison to the Probability score.  Normally, the ratio of EValue to Probability score is the search space size, which in the data we've seen is much lower.  It sounds to me like you also have a small search space, so I would expect the ratio to be smaller here as well.  Do you happen to know why the EValue scores are that high?

**Comment by wingkinlui** [comment]
Hi and thank you for your reply.

I do not fully understand the algorithm of EValue computation in MSPathFinderT. To my understanding, it is the summation of the probabilities of random sequences that could match as good as the target sequence in question. To my experience, the more the number of matched fragment to the target, the lower (better) would be the EValue.

In my data, most of the matched target had over 50 matched fragments, some of them even have over 100 matched fragments (the target sequence only have 136 residue). Such high number of matched fragments may account for the small EValues. It may sound absurd for me to still need to validate the proteoforms when the matched fragment is so abundant. The reason is that the protein I am studying, histone H3, is highly modified. Multiple PTMs could appear on various location on the sequence, creating a huge variety of proteoforms. Therefore, I would like to try using CD FDR to screen out proteoform mismatches.

I did not previously know that the ratio between Probability and EValue is correlated to the search space size. But it would also make sense to me, for I have allowed 8 site-unspecific-modifications (e.g. Monomethylation on lysine, anywhere in the sequence) and up to 7 modifications per match. Therefore, although I only have one sequence in the fasta, there could be over billions possible candidates.

**Comment by b-early** [comment]
Validating results is always a good idea, regardless of the scores or number of matching fragments, so that doesn't sound absurd at all.

To get the calculator to work, you'll need to use it on a score that has mostly positive values (any non-positive scores will be ignored).  My first instinct was to suggest using the Probability score, but on closer look that score is not what I thought it was.  The better hits have scores near 1, which is basically the opposite of what a statistical P-Value would imply (incidentally, my comment on the ratio of the E-Value to Probability being the search space is not entirely correct, though they are probably all related in some matter still).  Using the Probability score or some transform of it may still work, just take care to make sure that all the values are still positive and that higher scores are better scores.

The other option I can think of is to shift the E-Value scores in such a way that the decoy scores are positive.  This could be as simple as adding the worst (negative log transformed) decoy score to all scores (looking at the files you provide, -16.8000295283726 appears to be the worst).  I suspect this will work better than trying to use the Probability scores but as I am not familiar with how these scores are being calculated I cannot say for sure.

In any case, for the calculator to run you need A) a significant number of positive decoy scores (ideally all) and B) the better scores need to be the higher scores.  For the "Empirical" part of the FDR, this is sufficient to give accurate results (in theory, only B is required but due to the way it's programmed A is required otherwise the error you saw shows up and the process never finishes).  For the "Analytic" part of the FDR, the accuracy of the results depends on how closely the decoy scores follow a Gamma distribution, which incidentally is why positive values are required as Gamma distributions only contain positive values.

However, if all you want is an FDR cutoff point to filter out false results, if that cutoff point lies in the "Empirical" FDR range, then how accurate the Analytic FDR is is not very important.  The accuracy will affect the actual q-values calculated and shown in the results, but the actual results filtered out will be the same regardless.  With your data I suspect this will be the case if you use a 1% or higher FDR cutoff.  If you want to use a stricter cutoff than that it might move outside the Empirical FDR range.

Regardless of what score and transform you use, make sure the same is applied to the target scores as well.
